version: '3'

services:

  sila5kw:
  
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: sila5kw

    privileged: true
    restart: always

    #volumes:
        #- ./config/:/etc/inverter/

    devices:
      - /dev/ttyMOD2:/dev/ttyMOD2
      #- /dev/ttyMOD3:/dev/ttyMOD3

  sila8kw:

    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: sila8kw

    privileged: true
    restart: always

    #volumes:
        #- ./config/:/etc/inverter/

    devices:
      #- /dev/ttyMOD2:/dev/ttyMOD2
      - /dev/ttyMOD3:/dev/ttyMOD3
