FROM debian:stretch

# Update stretch repositories
RUN sed -i -e 's/deb.debian.org/archive.debian.org/g' \
           -e 's|security.debian.org|archive.debian.org/|g' \
           -e '/stretch-updates/d' /etc/apt/sources.list

RUN apt update && apt install -y \
        curl \
        git \
        build-essential \
        cmake \
        jq \
        mc \
        minicom \   
        htop \   
        mosquitto-clients

ADD sources/ /opt/
ADD config/ /etc/inverter/

RUN cd /opt/inverter-cli && \
    mkdir bin && cmake . && make && mv inverter_poller bin/

HEALTHCHECK \
    --interval=30s \
    --timeout=10s \
    --start-period=1m \
    --retries=3 \
  CMD /opt/healthcheck

# Copy the entrypoint script to the container.
COPY entrypoint.sh /entrypoint.sh

# Make the entrypoint script executable.
RUN chmod +x /entrypoint.sh

# Set the custom entrypoint script as the entrypoint.
#CMD /entrypoint.sh

# Set the custom entrypoint script as the entrypoint.
WORKDIR /
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
